ALTER TABLE `human_resource`.`employee`
ADD COLUMN `BIRTHDAY` DATE NOT NULL  AFTER `ROLE`;


ALTER TABLE `human_resource`.`leave_table`
ADD COLUMN `STATUS` ENUM('APPROVED', 'REJECTED', 'PENDING') NOT NULL DEFAULT 'PENDING' AFTER `EXPLANATION`;
