ALTER TABLE `EMPLOYEE`
    ADD COLUMN `BIRTHDAY` DATE AFTER `ROLE`;


ALTER TABLE `LEAVE`
    ADD COLUMN `STATUS` ENUM ('APPROVED', 'REJECTED', 'PENDING') NOT NULL DEFAULT 'PENDING' AFTER `EXPLANATION`;

CREATE UNIQUE INDEX  U__LEAVE__EMPLOYEE_ID__START_DATE__FINISH_DATE
ON `LEAVE`(EMPLOYEE_ID,START_DATE,FINISH_DATE)